Repository UQcsse3200/2024-studio-3, pull requests merged in 2024-10, with the labels that each got.

#382 Staion upgrade integration
  source/core/src/main/com/csse3200/game/components/items/ChopIngredientComponent.java
  source/core/src/main/com/csse3200/game/components/items/CookIngredientComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemTimerComponent.java
  source/core/src/main/com/csse3200/game/components/upgrades/RageUpgrade.java
  source/core/src/test/com/csse3200/game/components/items/ChopIngredientComponentTest.java
  source/core/src/test/com/csse3200/game/components/items/CookIngredientComponentTest.java
Labels: Team 5, sprint 3

#387 Station chopping freezing
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/station/IngredientStationHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationBinComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationItemHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationMealComponent.java
Labels: enhancement, Team 5, Task, Approved, sprint 3

#397 Station minor fixes
  source/core/assets/configs/recipe.json
  source/core/src/main/com/csse3200/game/components/items/ItemTexturePathGetter.java
  source/core/src/main/com/csse3200/game/components/station/IngredientStationHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationBinComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationMealComponent.java
  source/core/src/main/com/csse3200/game/components/station/loader/StationAcceptableItemsConfig.java
  source/core/src/test/com/csse3200/game/files/RecipeFileLoaderTest.java
Labels: bug, Team 5, Approved, sprint 3

#401 Spawn recipe shortcuts
  source/core/assets/images/stations/bin/bin_closed.png
  source/core/assets/images/stations/bin/bin_empty.png
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/services/PlayerService.java
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SpawnRecipeCommands.java
Labels: Team 5, sprint 3

#398 Fixed bug where game time on the background is not actually pausing when pause display is popped up
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/DayNightService.java
  source/core/src/main/com/csse3200/game/services/GameTime.java
Labels: bug, Team 2, Team 4, sprint 3

#424 Added more tests to IntroCutsceneTest.java and SensorComponentTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/IntroCutsceneTest.java
  source/core/src/test/com/csse3200/game/components/interaction/SensorComponentTest.java
Labels: Feature, sprint 3

#435 fixed the movement bug
  source/core/src/main/com/csse3200/game/components/tasks/PathFollowTask.java
Labels: Team 8, sprint 3

#437 Adding Moral Test and Javadocs
  source/core/src/main/com/csse3200/game/components/moral/MoralDayOne.java
  source/core/src/main/com/csse3200/game/components/moral/MoralDecision.java
  source/core/src/main/com/csse3200/game/components/moral/MoralTextDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/CustomerComponent.java
  source/core/src/main/com/csse3200/game/components/npc/CustomerManager.java
  source/core/src/main/com/csse3200/game/components/tasks/PathFollowTask.java
  source/core/src/test/com/csse3200/game/components/moral/MoralDayOneTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PathFollowTaskTest.java
Labels: Team 8, sprint 3

#442 Game tutorials updated
  source/core/src/main/com/csse3200/game/components/cutscenes/BackstoryCutsceneDisplay.java
  source/core/src/main/com/csse3200/game/components/tutorial/TutorialScreenDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/tutorial/TutorialScreenDisplayTest.java
Labels: Team 4, sprint 3

#447 Map levels
  .gitignore
  source/core/assets/images/hourglass.png
  source/core/assets/images/map/map_base.txt
  source/core/assets/images/map/map_five.txt
  source/core/assets/images/map/map_four.txt
  source/core/assets/images/map/map_one.txt
  source/core/assets/images/map/map_test.txt
  source/core/assets/images/map/map_test2.txt
  source/core/assets/images/map/map_three.txt
  source/core/assets/images/map/map_two.txt
  source/core/assets/images/money.png
  source/core/assets/images/ordersystem/acai_bowl_docket_vertical.png
  source/core/assets/images/ordersystem/banana_split_docket_vertical.png
  source/core/assets/images/ordersystem/fruit_salad_docket_vertical.png
  source/core/assets/images/ordersystem/pin_line2.png
  source/core/assets/images/ordersystem/salad_docket_vertical.png
  source/core/assets/images/ordersystem/steak_meal_docket_vertical.png
  source/core/assets/images/stations/benches/final.png
  source/core/assets/test/files/map_test.txt
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/MapLayout.java
  source/core/src/main/com/csse3200/game/areas/map/BenchGenerator.java
  source/core/src/main/com/csse3200/game/areas/map/BenchLayout.java
  source/core/src/main/com/csse3200/game/areas/map/Map.java
  source/core/src/main/com/csse3200/game/components/cutscenes/GoodEnd.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/GameBackgroundDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuBackground.java
  source/core/src/main/com/csse3200/game/components/ordersystem/DocketLineDisplay.java
  source/core/src/main/com/csse3200/game/components/ordersystem/DocketMealDisplay.java
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/entities/benches/Bench.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/TutorialScreen.java
  source/core/src/main/com/csse3200/game/services/LevelService.java
  source/core/src/main/com/csse3200/game/services/MapLayout.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/areas/map/BenchGeneratorTest.java
  source/core/src/test/com/csse3200/game/components/gameArea/GameBackgroundDisplayTest.java
  source/core/src/test/com/csse3200/game/components/gameArea/MainMenuTest.java
  source/core/src/test/com/csse3200/game/components/station/BenchTest.java
  source/core/src/test/com/csse3200/game/files/FileLoaderTest.java
  source/core/src/test/com/csse3200/game/services/MapLayoutTest.java
  source/logging.properties
Labels: Team 7, Feature

#471 Fixing scaling issue and exit button display
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
Labels: Team 6

#477 Team4/tutorial merge
  source/core/src/main/com/csse3200/game/components/cutscenes/BackstoryCutsceneDisplay.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneTextDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/maingame/RecipeCardDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/tutorial/Confirmationpopup.java
  source/core/src/main/com/csse3200/game/components/tutorial/TutorialScreenDisplay.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/TutorialScreen.java
  source/core/src/main/com/csse3200/game/services/MapLayout.java
  source/core/src/test/com/csse3200/game/components/ordersystem/MainGameActionsTest.java
Labels: Team 4, Sprint 4

#466 Animation bug fixes #464
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/components/player/PlayerItemSpriteManager.java
Labels: Team 5, Sprint 4

#490 Game start fix
  source/core/src/main/com/csse3200/game/services/LevelService.java
  source/core/src/test/com/csse3200/game/services/LevelServiceTest.java
Labels: Team 5, Sprint 4

#497 Team3/code smell components station game
  source/core/src/main/com/csse3200/game/components/station/FireExtinguisherHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/IngredientStationHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationCookingComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationItemHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationMealComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationProgressDisplay.java
  source/core/src/main/com/csse3200/game/components/station/StationServingComponent.java
  source/core/src/test/com/csse3200/game/components/station/FireExtinguisherHandlerComponentTest.java
  source/core/src/test/com/csse3200/game/components/station/StationChoppingComponentTest.java
  source/core/src/test/com/csse3200/game/components/station/StationCollectionComponentTest.java
  source/core/src/test/com/csse3200/game/components/station/StationMealComponentTest.java
Labels: Team 3, Sprint 4

#514 Interaction rewrite
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/SensorComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryDisplayHoverComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/station/StationProgressDisplay.java
  source/core/src/main/com/csse3200/game/entities/benches/Bench.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/StationFactory.java
  source/core/src/main/com/csse3200/game/services/InteractableService.java
  source/core/src/main/com/csse3200/game/services/MapLayout.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/components/interaction/CustomerSensorComponentTest.java
  source/core/src/test/com/csse3200/game/components/interaction/InteractionComponentTest.java
  source/core/src/test/com/csse3200/game/components/interaction/SensorComponentTest.java
  source/core/src/test/com/csse3200/game/services/MapLayoutTest.java
Labels: Team 5, Sprint 4

#525 Created LevelFactoryTest.java and added tests for Day2CutsceneTest,java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneArea.java
  source/core/src/main/com/csse3200/game/components/levels/LevelComponent.java
  source/core/src/test/com/csse3200/game/components/cutscenes/Day2CutsceneTest.java
  source/core/src/test/com/csse3200/game/entities/factories/LevelFactoryTest.java
Labels: enhancement, Feature, Sprint 4

#521 Added tests for the station bin component
  source/core/src/test/com/csse3200/game/components/station/StationBinComponentTest.java
Labels: Team 5, Sprint 4

#517 Allow meals to be created for customers that spawn at each level and fixed spawn times a little
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/levels/LevelComponent.java
Labels: bug, Team 1, Sprint 4

#530 Ammended station UI and Hitbox fixing
  source/core/assets/images/inventory_ui/chop_key.png
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/components/player/InventoryDisplayHoverComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/station/StationMealComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/rendering/AnimationRenderComponent.java
Labels: Team 5, Sprint 4

#542 Team7 improvements
  source/core/assets/images/map/map_five.txt
  source/core/assets/images/map/map_four.txt
  source/core/assets/images/map/map_one.txt
  source/core/assets/images/map/map_three.txt
  source/core/assets/images/map/map_two.txt
  source/core/assets/images/stations/benches/single.png
  source/core/src/main/com/csse3200/game/areas/map/BenchGenerator.java
  source/core/src/main/com/csse3200/game/services/MapLayout.java
  source/core/src/test/com/csse3200/game/services/MapLayoutTest.java
Labels: Team 7, Sprint 4

#545 Team1/finalsprint - fixing a javadoc error
  source/core/src/main/com/csse3200/game/components/station/PlateStationHandlerComponent.java
Labels: Team 1, Sprint 4

#557 Tutorials start at Level 0
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/tutorial/TutorialScreenDisplay.java
  source/core/src/main/com/csse3200/game/services/LevelService.java
  source/core/src/test/com/csse3200/game/components/tutorial/TutorialScreenDisplayTest.java
  source/core/src/test/com/csse3200/game/services/LevelServiceTest.java
Labels: Team 4, Sprint 4

#563 Team3/code smells components ordersystem
  h
  source/core/src/main/com/csse3200/game/components/ordersystem/ActiveAnimalsManager.java
  source/core/src/main/com/csse3200/game/components/ordersystem/Docket.java
  source/core/src/main/com/csse3200/game/components/ordersystem/DocketLineDisplay.java
  source/core/src/main/com/csse3200/game/components/ordersystem/DocketMealDisplay.java
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderBtnDisplay.java
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplay.java
  source/core/src/main/com/csse3200/game/components/ordersystem/OrderActions.java
  source/core/src/main/com/csse3200/game/components/ordersystem/OrderManager.java
  source/core/src/main/com/csse3200/game/components/ordersystem/TicketDetails.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/TutorialScreen.java
  source/core/src/test/com/csse3200/game/components/ordersystem/MainGameActionsTest.java
  source/core/src/test/com/csse3200/game/components/ordersystem/MainGameOrderBtnDisplayTest.java
  source/core/src/test/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplayTest.java
  source/core/src/test/com/csse3200/game/components/ordersystem/OrderActionsTest.java
  source/core/src/test/com/csse3200/game/components/ordersystem/OrderManagerTests.java
Labels: Team 3, Sprint 4

#576 Modifying recipe timings and fixing a bug with customer spawn timings
  source/core/assets/configs/recipe.json
  source/core/src/main/com/csse3200/game/components/levels/LevelComponent.java
  source/core/src/test/com/csse3200/game/files/RecipeFileLoaderTest.java
Labels: bug, Team 1, Sprint 4

#580 Fixing black box bug
  source/core/src/main/com/csse3200/game/rendering/AnimationRenderComponent.java
Labels: bug, Team 8, Sprint 4

#586 Fixed warnings in MainMenuDisplay.java and MainMenuBackground.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuBackground.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
Labels: enhancement, Sprint 4

#585 Multiple bug fixes and level 0 feature integration
  source/core/src/main/com/csse3200/game/components/cutscenes/Cutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/levels/LevelComponent.java
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplay.java
  source/core/src/main/com/csse3200/game/components/tutorial/TutorialScreenDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/TutorialScreen.java
  source/core/src/test/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplayTest.java
  source/core/src/test/com/csse3200/game/components/tutorial/TutorialScreenDisplayTest.java
Labels: Team 4, Sprint 4

#575 Reduce map loading time and optimisation
  source/core/assets/images/map/map_five.txt
  source/core/assets/images/map/map_four.txt
  source/core/assets/images/map/map_one.txt
  source/core/assets/images/map/map_two.txt
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/map/BenchGenerator.java
  source/core/src/main/com/csse3200/game/components/items/ChopIngredientComponent.java
  source/core/src/main/com/csse3200/game/components/items/CookIngredientComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemTexturePathGetter.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryDisplayHoverComponent.java
  source/core/src/main/com/csse3200/game/entities/benches/Bench.java
  source/core/src/main/com/csse3200/game/services/MapLayout.java
  source/core/src/test/com/csse3200/game/areas/map/BenchGeneratorTest.java
  source/core/src/test/com/csse3200/game/services/MapLayoutTest.java
Labels: Team 2, Sprint 4

#603 Fixed code smells for services
  source/core/assets/saves/02-10-2024_13-01-11.json
  source/core/assets/saves/02-10-2024_13-12-38.json
  source/core/assets/saves/03-10-2024_10-17-38.json
  source/core/assets/saves/03-10-2024_12-07-15.json
  source/core/assets/saves/12-10-2024_08-55-15.json
  source/core/assets/saves/12-10-2024_08-59-38.json
  source/core/assets/saves/12-10-2024_09-01-22.json
  source/core/assets/saves/12-10-2024_09-02-17.json
  source/core/assets/saves/begin.json
  source/core/assets/saves/saveFile.json
  source/core/assets/saves/testLoad.json
  source/core/assets/saves/testSave
  source/core/assets/saves/testSave.json
  source/core/src/main/com/csse3200/game/components/maingame/CheckWinLoseComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/services/DayNightService.java
  source/core/src/main/com/csse3200/game/services/GameTime.java
  source/core/src/main/com/csse3200/game/services/InteractableService.java
  source/core/src/main/com/csse3200/game/services/LevelService.java
  source/core/src/main/com/csse3200/game/services/MapLayout.java
  source/core/src/main/com/csse3200/game/services/RandomComboService.java
  source/core/src/main/com/csse3200/game/services/SaveGame.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/components/CheckWinLoseComponentTest.java
  source/core/src/test/com/csse3200/game/services/DayNightServiceTest.java
  source/core/src/test/com/csse3200/game/services/LevelServiceTest.java
  source/core/src/test/com/csse3200/game/services/MapLayoutTest.java
  source/core/src/test/com/csse3200/game/services/PlayerServiceTest.java
  source/core/src/test/com/csse3200/game/services/RandomComboServiceTest.java
  source/core/src/test/com/csse3200/game/services/SaveLoadServiceTest.java
Labels: Team 6, Sprint 4

#606 Fully Integrates Win/Loss Logic into Game and Ensures Days Iterate Correctly
  source/core/src/main/com/csse3200/game/components/maingame/CheckWinLoseComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/screens/MoralDecisionDisplay.java
  source/core/src/main/com/csse3200/game/services/DayNightService.java
  source/core/src/test/com/csse3200/game/components/CheckWinLoseComponentTest.java
  source/core/src/test/com/csse3200/game/services/DayNightServiceTest.java
Labels: Team 6, Sprint 4

#607 Improve load game
  source/core/assets/saves/02-10-2024_13-01-11.json
  source/core/assets/saves/02-10-2024_13-12-38.json
  source/core/assets/saves/03-10-2024_10-17-38.json
  source/core/assets/saves/03-10-2024_12-07-15.json
  source/core/assets/saves/12-10-2024_08-55-15.json
  source/core/assets/saves/12-10-2024_08-59-38.json
  source/core/assets/saves/12-10-2024_09-01-22.json
  source/core/assets/saves/12-10-2024_09-02-17.json
  source/core/assets/saves/Hey.json
  source/core/assets/saves/MySave.json
  source/core/assets/saves/WUJWDIIJWAD.json
  source/core/assets/saves/saveFile.json
  source/core/assets/saves/testSave
  source/core/assets/saves/testSave.json
  source/core/src/main/com/csse3200/game/components/maingame/PauseMenuActions.java
  source/core/src/main/com/csse3200/game/components/maingame/PauseMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/TextPopup.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/LoadGameDisplay.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/test/com/csse3200/game/services/SaveLoadServiceTest.java
Labels: Team 6, Sprint 4

#619 Improves LoadGameDisplay UI
  source/core/src/main/com/csse3200/game/components/settingsmenu/LoadGameDisplay.java
Labels: Team 6, Sprint 4

#616 Fixed bug where plate would be left in the station after combining
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationMealComponent.java
Labels: bug, Team 5, Sprint 4

#546 Fixed majority of code smells
  source/core/src/main/com/csse3200/game/components/station/StationItemHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/loader/StationAcceptableItemsConfig.java
  source/core/src/main/com/csse3200/game/components/station/loader/StationAcceptableItemsGetter.java
  source/core/src/test/com/csse3200/game/components/station/loader/StationAcceptableItemsGetterTest.java
Labels: Team 5, Sprint 4

#624 Moral integrations
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/cutscenes/Cutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/MoralDay1Cutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/MoralDay2Cutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/MoralDay3Cutscene.java
  source/core/src/main/com/csse3200/game/components/maingame/CheckWinLoseComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/maingame/TextDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/moral/MoralDecision.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/station/StationItemHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/loader/StationAcceptableItemsConfig.java
  source/core/src/main/com/csse3200/game/components/station/loader/StationAcceptableItemsGetter.java
  source/core/src/main/com/csse3200/game/components/tutorial/Confirmationpopup.java
  source/core/src/main/com/csse3200/game/components/tutorial/TutorialScreenDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/TutorialScreen.java
  source/core/src/main/com/csse3200/game/services/DayNightService.java
  source/core/src/test/com/csse3200/game/components/TextDisplayTest.java
  source/core/src/test/com/csse3200/game/components/moral/MoralDecisionTest.java
  source/core/src/test/com/csse3200/game/components/station/loader/StationAcceptableItemsGetterTest.java
  source/core/src/test/com/csse3200/game/services/DayNightServiceTest.java
Labels: Team 8, Sprint 4

#635 Extending Tutorials, Reimplementing missing popup, Tutorials TextDisplay fix
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/maingame/TextDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/tutorial/TutorialScreenDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/TutorialScreen.java
  source/core/src/test/com/csse3200/game/components/tutorial/TutorialScreenDisplayTest.java
Labels: bug, enhancement, Team 4, Sprint 4

#631 Moral smells
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/CustomerBehaviorComponent.java
  source/core/src/main/com/csse3200/game/components/moral/MoralDecision.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/PathFollowTask.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/test/com/csse3200/game/components/moral/MoralDecisionTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PathFollowTaskTest.java
Labels: Team 8, Sprint 4

#636 Code Smells
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/CustomerBehaviorComponent.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneActions.java
  source/core/src/main/com/csse3200/game/components/cutscenes/MoralDay2Cutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/MoralDay3Cutscene.java
  source/core/src/main/com/csse3200/game/components/moral/MoralDecision.java
  source/core/src/main/com/csse3200/game/components/moral/MoralDecisionDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/CustomerComponent.java
  source/core/src/main/com/csse3200/game/components/npc/CustomerPositionManagerComponent.java
  source/core/src/main/com/csse3200/game/components/npc/GhostAnimationController.java
  source/core/src/main/com/csse3200/game/components/upgrades/DancePartyUpgrade.java
  source/core/src/test/com/csse3200/game/components/npc/CustomerPositionManagerComponentTest.java
  source/core/src/test/com/csse3200/game/screens/MoralDecisionDisplayTest.java
Labels: Team 8, Sprint 4

#637 Fixing Moral CutScene Code Smells
  source/core/src/main/com/csse3200/game/components/cutscenes/MoralDay1Cutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/MoralDay2Cutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/MoralDay3Cutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/MoralDay4Cutscene.java
Labels: Team 8, Sprint 4

#638 EndDayDisplay Code Smells
  source/core/src/main/com/csse3200/game/components/maingame/EndDayDisplay.java
Labels: Team 8, Sprint 4

#647 Team3/code smells components npc
  source/core/src/main/com/csse3200/game/components/npc/CustomerManager.java
  source/core/src/main/com/csse3200/game/components/npc/GhostPositionManagerComponent.java
  source/core/src/test/com/csse3200/game/components/npc/CustomerComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/CustomerManagerTest.java
  source/core/src/test/com/csse3200/game/components/npc/PersonalCustomerEnumsTest.java
Labels: Team 3, Sprint 4

#653 Pressing Enter crashes the game out of bounds
  source/core/src/main/com/csse3200/game/components/maingame/TextDisplay.java
  source/core/src/main/com/csse3200/game/components/tutorial/TutorialScreenDisplay.java
Labels: bug, Team 4, Sprint 4

#648 Team5 station test coverage
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SpawnRecipeCommandsTest.java
Labels: Team 5, Sprint 4

#658 Team3/code smells componentscutscenes
  source/core/src/main/com/csse3200/game/components/cutscenes/BackstoryCutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/BadEndCutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/Cutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneActions.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneArea.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneFactory.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneTextDisplay.java
  source/core/src/main/com/csse3200/game/components/cutscenes/Day2Cutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/Day3Cutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/GoodEndCutscene.java
  source/core/src/main/com/csse3200/game/components/cutscenes/IntroCutscene.java
  source/core/src/test/com/csse3200/game/components/cutscenes/AnimatedSceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/BackgroundCutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/BackstoryCutsceneDisplayTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/BackstoryCutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/BadEndCutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/CutsceneScreenDisplayTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/CutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/Day2CutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/Day3CutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/Day4CutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/GoodEndCutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/GoodEndTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/IntroCutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/LoseEndTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/MoralDay1CutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/MoralDay2CutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/MoralDay3CutsceneTest.java
  source/core/src/test/com/csse3200/game/components/cutscenes/MoralDay4CutsceneTest.java
Labels: Team 3, Sprint 4

#657 Moral polish test
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/maingame/MoralDisplayTemp.java
  source/core/src/main/com/csse3200/game/components/maingame/TextDisplay.java
  source/core/src/main/com/csse3200/game/screens/MoralDecisionDisplay.java
  source/core/src/test/com/csse3200/game/components/maingame/TestTextDisplayMoral.java
  source/core/src/test/com/csse3200/game/components/maingame/TextDisplayTest.java
Labels: Team 8, Sprint 4

#662 Code smells for game/areas
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/map/BenchGenerator.java
  source/core/src/test/com/csse3200/game/areas/GameAreaTest.java
Labels: Team 5, Sprint 4

#667 Code smells, tutorial
  source/core/src/main/com/csse3200/game/components/tutorial/Confirmationpopup.java
  source/core/src/main/com/csse3200/game/components/tutorial/KeybindsButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/tutorial/TutorialScreenDisplay.java
Labels: Team 5, Sprint 4

#672 PlateComponent final tests
  source/core/src/test/com/csse3200/game/components/items/PlateComponentTest.java
Labels: Team 1, Sprint 4

#676 Pressing Enter to advance when handling tutorialskeys and cleanups
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplay.java
  source/core/src/main/com/csse3200/game/components/tutorial/TutorialScreenDisplay.java
  source/core/src/main/com/csse3200/game/screens/TutorialScreen.java
Labels: bug, Team 4, Sprint 4
