Repository UQcsse3200/2024-studio-3, pull requests merged in 2024-08, with the labels that each got.

#73 Team7 map
  source/core/assets/images/box_boy.png
  source/core/assets/images/box_boy_leaf.png
  source/core/assets/images/chef_player.png
  source/core/assets/images/ghost_1.png
  source/core/assets/images/ghost_2.png
  source/core/assets/images/ghost_3.png
  source/core/assets/images/ghost_king.png
  source/core/assets/images/grass_1.png
  source/core/assets/images/grass_2.png
  source/core/assets/images/grass_3.png
  source/core/assets/images/hex_grass_1.png
  source/core/assets/images/hex_grass_2.png
  source/core/assets/images/hex_grass_3.png
  source/core/assets/images/iso_grass_1.png
  source/core/assets/images/iso_grass_2.png
  source/core/assets/images/iso_grass_3.png
  source/core/assets/images/stations/bench.png
  source/core/assets/images/stations/benches/bench1.png
  source/core/assets/images/stations/benches/bench2.png
  source/core/assets/images/stations/benches/bench3-5.png
  source/core/assets/images/stations/benches/bench4.png
  source/core/assets/images/stations/benches/bench6.png
  source/core/assets/images/stations/benches/bench7.png
  source/core/assets/images/stations/border.png
  source/core/assets/images/stations/bottom_border.png
  source/core/assets/images/stations/bottom_border_wall.png
  source/core/assets/images/stations/bottom_door_left_part.png
  source/core/assets/images/stations/bottom_door_right_part.png
  source/core/assets/images/stations/bottom_left_inv.png
  source/core/assets/images/stations/bottom_right_inv.png
  source/core/assets/images/stations/door.png
  source/core/assets/images/stations/glassdisplay.png
  source/core/assets/images/stations/left_border.png
  source/core/assets/images/stations/right_border.png
  source/core/assets/images/stations/top_border.png
  source/core/assets/images/stations/top_border_wall.png
  source/core/assets/images/stations/top_door_left_part.png
  source/core/assets/images/stations/top_door_right_part.png
  source/core/assets/images/terrain_hex.png
  source/core/assets/images/terrain_iso_grass.atlas
  source/core/assets/images/terrain_iso_grass.png
  source/core/assets/images/test.atlas
  source/core/assets/images/test.png
  source/core/assets/images/tiles/blue_tile.png
  source/core/assets/images/tiles/orange_tile.png
  source/core/assets/images/tree.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/entities/benches/Bench.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/StationFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/desktop/out/production/resources/images/stations/glassdisplay.png
Labels: Sprint 1, Team 7, Feature

#92 Team6/items Full item catalogue and functionality
  source/core/assets/configs/ingredients.json
  source/core/assets/images/ingredients/burnt_beef.png
  source/core/assets/images/ingredients/chopped_acai.png
  source/core/assets/images/ingredients/chopped_banana.png
  source/core/assets/images/ingredients/chopped_chocolate.png
  source/core/assets/images/ingredients/chopped_cucumber.png
  source/core/assets/images/ingredients/chopped_lettuce.png
  source/core/assets/images/ingredients/chopped_strawberry.png
  source/core/assets/images/ingredients/chopped_tomato.png
  source/core/assets/images/ingredients/cooked_beef.png
  source/core/assets/images/ingredients/cooked_fish.png
  source/core/assets/images/ingredients/raw_acai.png
  source/core/assets/images/ingredients/raw_banana.png
  source/core/assets/images/ingredients/raw_beef.png
  source/core/assets/images/ingredients/raw_chocolate.png
  source/core/assets/images/ingredients/raw_cucumber.png
  source/core/assets/images/ingredients/raw_fish.png
  source/core/assets/images/ingredients/raw_lettuce.png
  source/core/assets/images/ingredients/raw_strawberry.png
  source/core/assets/images/ingredients/raw_tomato.png
  source/core/assets/images/meals/acai_bowl.png
  source/core/assets/images/meals/banana_split.png
  source/core/assets/images/meals/fruit_salad.png
  source/core/assets/images/meals/salad.png
  source/core/assets/images/meals/steak_meal.png
  source/core/assets/images/raw_chocolate.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/items/CookIngredientComponent.java
  source/core/src/main/com/csse3200/game/components/items/IngredientComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemType.java
  source/core/src/main/com/csse3200/game/components/items/MealComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/events/CookingAndServingHandler.java
  source/core/src/main/com/csse3200/game/rendering/TextureRenderComponent.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/test/com/csse3200/game/components/items/IngredientComponentTest.java
  source/core/src/test/com/csse3200/game/components/items/ItemComponentTest.java
  source/core/src/test/com/csse3200/game/components/items/ItemFactoryTest.java
  source/core/src/test/com/csse3200/game/components/items/MealComponentTest.java
  source/core/src/test/com/csse3200/game/events/CookingAndServingHandlerTest.java
Labels: Sprint 1, Team 6, Feature

#96 Customer Entity and End of Day Summary
  source/core/assets/configs/Customer.json
  source/core/assets/images/animal_images/goat.png
  source/core/assets/images/animal_images/goose.png
  source/core/assets/images/animal_images/gorilla.png
  source/core/assets/images/animal_images/monkey.png
  source/core/assets/images/animal_images/snow_wolf.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/maingame/EndDayDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/CustomerComponent.java
  source/core/src/main/com/csse3200/game/components/npc/CustomerPositionManagerComponent.java
  source/core/src/main/com/csse3200/game/components/npc/GhostPositionManagerComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/PathFollowTask.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseCustomerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/CustomerPersonalityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/npc/CustomerPositionManagerComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PathFollowTaskTest.java
Labels: Sprint 1, Team 8
