Repository UQcsse3200/2024-studio-3, pull requests merged in 2024-09, with the labels that each got.

#180 Team4/sprint2 currency extended
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/ordersystem/Docket.java
  source/core/src/main/com/csse3200/game/components/ordersystem/DocketLineDisplay.java
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderBtnDisplay.java
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplay.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/PlayerService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/components/ordersystem/MainGameOrderBtnDisplayTest.java
  source/core/src/test/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplayTest.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
  source/core/src/test/com/csse3200/game/components/station/FireExtinguisherHandlerComponentTest.java
Labels: Team 4, Task, Sprint 2

#186 Plate Component Feature
  source/core/assets/images/platecomponent/cleanplate.png
  source/core/assets/images/platecomponent/dirtyplate.png
  source/core/assets/images/platecomponent/stackedplates/1plates.png
  source/core/assets/images/platecomponent/stackedplates/2plates.png
  source/core/assets/images/platecomponent/stackedplates/3plates.png
  source/core/assets/images/platecomponent/stackedplates/4plates.png
  source/core/assets/images/platecomponent/stackedplates/5plates.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/items/ItemType.java
  source/core/src/main/com/csse3200/game/components/items/PlateComponent.java
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderBtnDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/PlateFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/test/com/csse3200/game/components/items/PlateComponentTest.java
  source/core/src/test/com/csse3200/game/components/station/FireExtinguisherHandlerComponentTest.java
Labels: Team 4, Feature, Sprint 2

#192 106 level system EXTENDED
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/levels/LevelComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/EndDayDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/PersonalCustomerEnums.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/LevelService.java
Labels: enhancement, Team 4, Feature, Sprint 2

#198 Added secondary constructor for inventory componet for Stations
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
Labels: Team 5, Sprint 2

#193 Plate Component Feature Repull
  source/core/assets/images/platecomponent/cleanplate.png
  source/core/assets/images/platecomponent/dirtyplate.png
  source/core/assets/images/platecomponent/stackedplates/1plates.png
  source/core/assets/images/platecomponent/stackedplates/2plates.png
  source/core/assets/images/platecomponent/stackedplates/3plates.png
  source/core/assets/images/platecomponent/stackedplates/4plates.png
  source/core/assets/images/platecomponent/stackedplates/5plates.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/items/ItemType.java
  source/core/src/main/com/csse3200/game/components/items/PlateComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/entities/factories/PlateFactory.java
  source/core/src/test/com/csse3200/game/components/items/PlateComponentTest.java
Labels: Team 4, Feature, Sprint 2

#215 Improved main title screen
  source/core/assets/flat-earth/skin/flat-earth-ui.json
  source/core/assets/images/Beastly.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
Labels: Team 7, Feature, Sprint 2

#227 Interaction bug fix
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
Labels: bug, Sprint 2

#236 Merge team4/sprint into main with docket resizing and visual aspects.
  source/core/assets/images/ordersystem/acai_bowl_docket.png
  source/core/assets/images/ordersystem/banana_split_docket.png
  source/core/assets/images/ordersystem/fruit_salad_docket.png
  source/core/assets/images/ordersystem/pin_line.png
  source/core/assets/images/ordersystem/salad_docket.png
  source/core/assets/images/ordersystem/steak_meal_docket.png
  source/core/src/main/com/csse3200/game/components/ordersystem/DocketLineDisplay.java
  source/core/src/main/com/csse3200/game/components/ordersystem/DocketMealDisplay.java
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplayTest.java
Labels: Team 4, Task, Sprint 2

#235 Station Animations
  source/core/assets/images/stations/blender.png
  source/core/assets/images/stations/cuttingboard.png
  source/core/assets/images/stations/fridge.png
  source/core/assets/images/stations/oven.png
  source/core/assets/images/stations/oven/oven.atlas
  source/core/assets/images/stations/oven/oven.png
  source/core/assets/images/stations/producebasket.png
  source/core/assets/images/stations/stove.png
  source/core/assets/images/stations/stove/stove.atlas
  source/core/assets/images/stations/stove/stove.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplay.java
  source/core/src/main/com/csse3200/game/components/ordersystem/OrderActions.java
  source/core/src/main/com/csse3200/game/components/ordersystem/TicketDetails.java
  source/core/src/main/com/csse3200/game/components/station/StationAnimationController.java
  source/core/src/main/com/csse3200/game/components/station/StationServingComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/StationFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplayTest.java
  source/core/src/test/com/csse3200/game/entities/factories/StationFactoryTest.java
Labels: Team 5, Feature, Sprint 2

#246 Fixing endday
  source/core/src/main/com/csse3200/game/components/levels/LevelComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/EndDayDisplay.java
Labels: Team 8

#257 Fixing Build and adding javadocs
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/maingame/CheckWinLoseComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/EndDayDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/TextDisplay.java
  source/core/src/main/com/csse3200/game/components/moral/MoralEnum.java
  source/core/src/main/com/csse3200/game/screens/MoralDecisionDisplay.java
Labels: Team 8

#256 Fixed the errors in the Javadocs which were causing main to break
  source/core/src/main/com/csse3200/game/components/maingame/CheckWinLoseComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/TextDisplay.java
Labels: bug, Sprint 2

#261 Bug fixes 259 and 260
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/services/DayNightService.java
Labels: bug, Sprint 2

#244 Customer Sensor Component
  source/core/src/main/com/csse3200/game/components/CustomerSensorComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/test/com/csse3200/game/components/interaction/CustomerSensorComponentTest.java
Labels: Team 3, Sprint 2

#299 Team5 Station Cleanup First Steps
  source/core/assets/configs/station.json
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/station/IngredientStationHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationBinComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationItemHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/loader/StationAcceptableItemsConfig.java
  source/core/src/main/com/csse3200/game/components/station/loader/StationAcceptableItemsGetter.java
  source/core/src/main/com/csse3200/game/entities/benches/Bench.java
  source/core/src/main/com/csse3200/game/entities/factories/StationFactory.java
  source/core/src/test/com/csse3200/game/components/station/StationItemHandlerComponentTest.java
  source/core/src/test/com/csse3200/game/components/station/loader/StationAcceptableItemsGetterTest.java
  source/core/src/test/com/csse3200/game/entities/factories/StationFactoryTest.java
Labels: Team 5, sprint 3

#342 Temp fix for memory and cpu usage
  source/core/src/main/com/csse3200/game/screens/MoralDecisionDisplay.java
Labels: bug, sprint 3

#343 Item changes #328
  source/core/assets/images/stations/benches/left_corner_shadow.png
  source/core/assets/images/stations/benches/shadow_bottom_top.png
  source/core/assets/images/stations/benches/single.png
  source/core/assets/images/stations/benches/top.png
  source/core/assets/images/stations/benches/top_shadows.png
  source/core/assets/images/stations/benches/vertical.png
  source/core/assets/images/stations/leaf_basket.png
  source/core/assets/images/stations/oven/oven.png
  source/core/assets/images/stations/producebasketalt.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/items/ChopIngredientComponent.java
  source/core/src/main/com/csse3200/game/components/items/CookIngredientComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemTexturePathGetter.java
  source/core/src/main/com/csse3200/game/components/items/ItemTimerComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/station/StationCollectionComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationCookingComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/StationFactory.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SpawnRecipeCommands.java
  source/core/src/test/com/csse3200/game/components/items/ChopIngredientComponentTest.java
  source/core/src/test/com/csse3200/game/components/items/CookIngredientComponentTest.java
  source/core/src/test/com/csse3200/game/components/items/ItemComponentTest.java
  source/core/src/test/com/csse3200/game/components/items/ItemFactoryTest.java
  source/core/src/test/com/csse3200/game/components/station/CookingComponentTest.java
  source/core/src/test/com/csse3200/game/components/station/StationChoppingComponentTest.java
  source/core/src/test/com/csse3200/game/components/station/StationCookingComponentTest.java
  source/core/src/test/com/csse3200/game/components/station/StationItemHandlerComponentTest.java
Labels: Team 5, sprint 3

#357 Team5 Ingredient Station Spawning and Combine Attempt Button
  source/core/assets/images/stations/baskets/basket_banana.png
  source/core/assets/images/stations/baskets/basket_cucumber.png
  source/core/assets/images/stations/baskets/basket_lettuce.png
  source/core/assets/images/stations/baskets/basket_strawberry.png
  source/core/assets/images/stations/baskets/basket_tomato.png
  source/core/assets/images/stations/producebasketalt.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/station/IngredientStationHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationBinComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationItemHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationMealComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationServingComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/StationFactory.java
  source/core/src/test/com/csse3200/game/components/player/KeyboardPlayerInputComponentTest.java
  source/core/src/test/com/csse3200/game/components/station/StationItemHandlerComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/StationFactoryTest.java
Labels: Team 3, Team 5, Task

#363 All Station Spawning and base Station Functionality
  source/core/assets/images/stations/baskets/basket_acai.png
  source/core/assets/images/stations/benches/garbage_bin.png
  source/core/assets/images/stations/chopping_board/choppingboard.png
  source/core/assets/images/stations/chopping_board/choppingboardbench.png
  source/core/assets/images/stations/fridge/fridge_choc.png
  source/core/assets/images/stations/fridge/fridge_meat.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/station/StationMealComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/StationFactory.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
Labels: Team 5, sprint 3

#367 366 customer movement extended
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/PathFollowTask.java
Labels: Team 8, sprint 3

#369 Bug fix for #161
  source/core/assets/images/player/boy_down_1.png
  source/core/assets/images/player/boy_down_2.png
  source/core/assets/images/player/boy_left_1.png
  source/core/assets/images/player/boy_left_2.png
  source/core/assets/images/player/boy_right_1.png
  source/core/assets/images/player/boy_right_2.png
  source/core/assets/images/player/boy_up_1.png
  source/core/assets/images/player/boy_up_2.png
  source/core/src/main/com/csse3200/game/components/npc/GhostPositionManagerComponent.java
  source/core/src/main/com/csse3200/game/components/ordersystem/Docket.java
  source/core/src/main/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplay.java
Labels: Team 4, sprint 3

#375 Tutorial popup when start button clicked
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/tutorial/Confirmationpopup.java
Labels: enhancement, Team 4, sprint 3
